name: Java CI

on: 
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      gradle_commands: build # default is build
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Wrap without version
        run: gradle wrapper
      - name: Build with Gradle
        run: ./gradlew ${{ env.gradle_commands }}

      - name: Upload zip and jar
        uses: actions/upload-artifact@v2
        with:
            name: Package
            path: build/libs
      - name: publish to artifactory
        uses: advancedcsg-open/action-jfrog-cli@master
        with:
            url: 'https://sigmadevelopmentteam.jfrog.io/artifactory/default-gradle-dev/'
            credentials type: 'apikey'
            apikey: ${{ secrets.RT_APIKEY }}
            args: u "build/libs/*" "/sigma/" --recursive=true